# SPDX-FileCopyrightText: Copyright 2025 Carabiner Systems, Inc
# SPDX-License-Identifier: Apache-2.0

project_name: bnd
version: 2

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy
    - /bin/bash -c 'if [ -n "$(git --no-pager diff --exit-code go.mod go.sum)" ]; then exit 1; fi'

gomod:
  proxy: true

builds:
  - id: bnd
    no_unique_dist_dir: true
    binary: bnd-{{ .Arch }}-{{ .Os }}
    main: ./cmd/bnd
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: amd64
    flags:
      - -trimpath

archives:
  - format: binary
    name_template: bnd-{{ .Arch }}-{{ .Os }}
    allow_different_binary_count: true

release:
  github:
    owner: puerco
    name: bnd
  prerelease: auto

changelog:
  disable: true
